version: '3.8'

services:
  api:
    build: .
    ports:
      - "8210:8210"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8210/"]
      interval: 30s
      timeout: 10s
      retries: 3