services:
  api:
    build: .
    ports:
      - "8210:8210"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8210/"]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-puppeteer:
    image: mcp/puppeteer
    ports:
      - "3000:3000"
    volumes:
      - ./mcp:/app/mcp
    environment:
      - NODE_ENV=development
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: '1gb'
    networks:
      - mcp-network

  mcp-github:
    image: mcp/github
    ports:
      - "3001:3001"
    volumes:
      - ./github:/app/github
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - mcp-network

  mcp-brave-search:
    image: mcp/brave-search
    ports:
      - "3002:3002"
    volumes:
      - ./brave-search:/app/brave-search
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    networks:
      - mcp-network

  mcp-sqlite:
    image: mcp/sqlite
    ports:
      - "3003:3003"
    volumes:
      - ./sqlite:/app/sqlite
      - ./data/sqlite:/var/lib/sqlite
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - SQLITE_DATABASE=/var/lib/sqlite/mcp.db
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
